### ISSUE TITLE
Issue with Asynchronous Code Evaluation in QuickJS

### ISSUE THREAD

**Issue by MarketingPip** [sebastianwessel/quickjs#48] opened 2024-09-09 23:21 UTC
**Title: Issue with Asynchronous Code Evaluation in QuickJS**

**Description:**

I am encountering an issue when trying to evaluate asynchronous JavaScript code using the `eval` function in the QuickJS engine. The code snippet below is intended to evaluate a string of JavaScript code asynchronously. However, it does not work as expected in QuickJS.

**Code:**

```javascript
let __EVAL = async (s) => {
    // Define a helper function that performs the evaluation and returns a promise
    const evalAsync = (code) => {
        return new Promise((resolve, reject) => {
            try {
                // Evaluate the code and resolve with the result
                resolve(eval(code));
            } catch (err) {
                reject(err);
            }
        });
    };

    // Construct the code string to be evaluated
    const codeString = `void (__EVAL = ${__EVAL.toString()}); (${s})`;

    // Use the helper function to evaluate the code asynchronously and return the result
    try {
        const result = await evalAsync(codeString);
        return result;
    } catch (error) {
        console.error('Error evaluating code:', error);
        return undefined; // or handle the error as needed
    }
};

// Example usage
(async () => {
    const result = await __EVAL('console');
    console.log(result); // Should return console
})();
```

**Issue:**

1. **`eval` Function**: QuickJS might not support the `eval` function in the same way as other environments. It seems that `eval` either does not work or behaves differently in QuickJS.
   
2. **Function Serialization**: The approach of serializing and deserializing the `__EVAL` function using `toString()` and `eval()` might not be compatible with QuickJS, leading to errors.

3. **Evaluation Scope**: There may be scoping issues or restrictions in QuickJS that prevent the proper evaluation of code within the asynchronous context.

4. **No outputs**: I can not debug this - as I have no outputs to help say what went wrong. (Is it me)?

**Expected Behavior:**

The code should successfully evaluate the string `'console'` and return the `console` object. In a fully compatible environment, the `console` object should be logged to the console.

**Actual Behavior:**

The code fails to evaluate correctly, and the `console` object is not returned as expected. The error handling logs an error message, but the exact nature of the problem remains unclear.

**Environment:**

- QuickJS version: v1.3.0
- Platform: Browser

**Steps to Reproduce:**

1. Copy and paste the provided code into a QuickJS environment.
2. Run the code.
3. Observe the output and error messages.

**Additional Information:**

- Please advise on any changes needed to make this code compatible with QuickJS.

Thank you for your assistance!

**Comment by sebastianwessel** [comment] 2024-09-10 09:00
No idea what you try to achieve with this code, but the console is a host function provided to the host.
Never tested it, but I guess `eval` in QucikJS only "knows" QuickJS functions & stuff - but not the injected ones.


Also, you create a kind of strange loop. Inject console from host to client, put this into an `eval` inside the client, and try to console output the returned console from eval...

I do not see an issue here, which should be fixed. The code you provided seems to be horribly wrong, tbh.

```
// Construct the code string to be evaluated
    const codeString = `void (__EVAL = ${__EVAL.toString()}); (${s})`;
```
^ void ? __EVAL.toString() inside the async __EVAL function - meaning you do a recursive thing without await -> endless loop

**Comment by MarketingPip** [comment] 2024-09-10 09:08
@sebastianwessel - this is just for a demo / play right now... tho I am trying to simulate this behaviour in quickjs - see [here](https://codepen.io/MarketingPipeline/pen/eYQwBmN) 

If I avoid using "void" I can eval things fine.... 

Tho this code is meant to throw endless loop etc (just as in demo of code I gave you). I do have a way to exit it (not that exact code but). Just wrote that code to explain issue...

**Comment by sebastianwessel** [comment] 2024-09-10 09:20
But, I really don't get the point, what you try to do, and why/for what you need to use eval.

**Comment by MarketingPip** [comment] 2024-09-10 09:30
@sebastianwessel - cause I have discovered a way to get inputs from user etc via prompt and my own input methods etc.... so I can build a "REPL" inside of quickjs. I mentioned this in other issues.....

**Comment by MarketingPip** [comment] 2024-09-10 09:41
@sebastianwessel - closing this issue (my stupidity). I guess I COULD catch the log of functions as needed.... Just my function that formatted into string didn't do it properly... lol

That said - yes REPL supported is do able as before. (as given in demo now) ;)

**Comment by MarketingPip** [comment] 2024-09-10 10:12
@sebastianwessel - tho there still seems issue lies within "void"... I am thinking maybe this error might give some inside...

```json
Serializing native function: anonymous @log.js
```

**Comment by MarketingPip** [comment] 2024-09-10 23:59
@sebastianwessel - if you can try running this for a eval()

```js
var __EVAL = (s) => eval(`void (__EVAL = ${__EVAL.toString()}); ${s}`);

console.log(__EVAL("1+"1))
```

**Comment by sebastianwessel** [comment] 2024-09-11 08:17
It is returning 2 (after fixing the typo in `console.log(__EVAL("1+"1))` - `"1+1"`).

But what is the point here? Why not simply `const __EVAL = (s)=> eval(s)`

This whole self-redefining stuff of eval, is something which is done in regular node apps, when they need to somehow prevent, that the executed code is changing the eval function itself.

But as you are in the wasm-QuickJS-sandbox, you do not need to take care of it imo.
If someone is overwriting it - well, that is fine. Only his code inside the guest ystem might break, but not the root system or other users...

**Closed by sebastianwessel** 2024-09-11 08:17 UTC

**Comment by MarketingPip** [comment] 2024-09-17 04:22
@sebastianwessel - this is still an issue... I am now sure how you got this to work....

```js
var __EVAL = s => eval(`void (__EVAL = ${__EVAL.toString()}); ${s}`);

function evaluate(expr) {
    try {
        const result = __EVAL(expr);
        console.log(expr, '===>', result)
    } catch(err) {
        console.log(expr, 'ERROR:', err.message)
    }
}

evaluate('var ten = 10')
evaluate('function cube(x) { return x ** 3 }')
evaluate('ten + cube(3)')
evaluate('console.log("SIDE EFFECT")')
evaluate('let twenty = 20')
evaluate('twenty + 40') // NO PROBLEM :D
```

I am seeing 

```js
"ERROR:"
"expecting ']'"
```

I need to use void...

**Comment by MarketingPip** [comment] 2024-09-17 04:35
@sebastianwessel - I expect you were seeing this: 
![image](https://github.com/user-attachments/assets/42ca5566-f712-42e8-825b-4353ff281a26)

Without the expect messages....


First result should have returned undefined... etc

**Comment by sebastianwessel** [comment] 2024-09-23 10:52
Here is the output:

```cmd
var ten = 10 ===> undefined
function cube(x) { return x ** 3 } ===> undefined
ten + cube(3) ===> 37
SIDE EFFECT
console.log("SIDE EFFECT") ===> undefined
let twenty = 20 ===> undefined
twenty + 40 ===> 60
```

Try to create a minimal example, based on the basic example in the repo

**Comment by MarketingPip** [comment] 2024-09-23 11:18
@sebastianwessel - is there any way I can reproduce void so I can create a true context preserving eval method? The same as example I gave you?

**Comment by sebastianwessel** [comment] 2024-09-23 11:41
```ts
import { quickJS } from '../../src/index.js'

// General setup like loading and init of the QuickJS wasm
// It is a ressource intensive job and should be done only once if possible
const { createRuntime } = await quickJS()

// Create a runtime instance each time a js code should be executed
const { evalCode } = await createRuntime({
	allowFetch: true, // inject fetch and allow the code to fetch data
	allowFs: true, // mount a virtual file system and provide node:fs module
	env: {
		MY_ENV_VAR: 'env var value',
	},
})

await evalCode(`
var __EVAL = s => eval(\`void (__EVAL = \${__EVAL.toString()}); \${s}\`);

function evaluate(expr) {
    try {
        const result = __EVAL(expr);
        console.log(expr, '===>', result)
    } catch(err) {
        console.log(expr, 'ERROR:', err.message)
    }
}

evaluate('var ten = 10')
evaluate('function cube(x) { return x ** 3 }')
evaluate('ten + cube(3)')
evaluate('console.log("SIDE EFFECT")')
evaluate('let twenty = 20')
evaluate('twenty + 40') // NO PROBLEM :D
  
export default await fn()
`)
```

<img width="374" alt="Bildschirmfoto 2024-09-23 um 12 41 20" src="https://github.com/user-attachments/assets/40a88970-5364-48ef-859b-5c66cf526098">

**Comment by MarketingPip** [comment] 2024-09-23 22:03
@sebastianwessel - hmmm weird... I am not getting the same usage....

![image](https://github.com/user-attachments/assets/e45897bd-bff4-403c-ad8e-c85903b5ac47)


I am using polyfill for symbol dispose but I doubt that has any effects here.

Thought I was going crazy but lol. Do you have this working in browser (assuming)?

**Comment by sebastianwessel** [comment] 2024-09-24 11:13
Just to clarify, it’s important to note that you're essentially on your own with this approach. I don't see the value in using `eval` within a QuickJS runtime that is running inside a browser. QuickJS itself is meant to be a safer and more controlled alternative to `eval`. Instead, consider starting a fresh instance of QuickJS.

If you're encountering an issue, please provide a complete minimal example that reproduces the bug so it can be properly diagnosed.

Please keep in mind that I'm working on this in my free time, and it's important for me to stay focused on the core library to make the best use of my available time. Efficiency is key, so I appreciate your understanding.

**Comment by MarketingPip** [comment] 2024-09-24 20:41
@sebastianwessel - cause I am the process of building a REPL inside of it.... 

I need eval to do this.


The example of the code I gave you does NOT work on my end - but for some reason does on yours.... 

Again not sure why I'm seeing the expecting errors and you are not... curious if you had this working on browser.

**Comment by MarketingPip** [comment] 2024-09-25 09:17
@sebastianwessel - I ended up getting in working - had to re-write a new function (not sure why I am facing those issues) - maybe due to me using poly fill or? (required for my device)

That said - just wanted to share with you results of a "REPL" in browser using quickjs.

![image](https://github.com/user-attachments/assets/e1079b6b-efba-4cf2-be39-b0fe6e0ca25d)

ps; don't mind the "" should be a prompt etc lol
