### ISSUE TITLE
[Feature Request]: Set "root" directory.

### ISSUE THREAD

**Issue by MarketingPip** [sebastianwessel/quickjs#43] opened 2024-08-20 04:37 UTC
Currently root directory is defined as "src".... This is a issue when working with custom fs.. 

As to use a import you need to be in "src" like example

```md
import {test} from "./src/test.js"
```

which might be confusing to a user who thinks they are in "cwd" as "/".

In options run time would be great if we could define this...

Rather then placing all files in "src" to achieve this. Which still doesn't handle cases like readFile etc...

**Comment by sebastianwessel** [comment] 2024-08-20 13:50
I do not really get the issue.
The default `evalCode` is "thinking", that it resists in the file `src/index.js`. This means, `cwd` is `/src`.
Custom source files should be simply mounted into `/src`.
From here, as relative imports are used, it will not be `./src/test.js` - it will be `./test.js`, and all source files are below `src`

```js
mountFs: {
		src: {
			'custom.js': `export const relativeImportFunction = ()=>'Hello from relative import function'`,
		},
	},
```

There should also be no issue with the mounted files, as they are also relative to each other, and they should not reference the `src/index.js` - cycling deps

**Comment by MarketingPip** [comment] 2024-08-20 13:57
@sebastianwessel - actually here to report an issue regarding this..  


If I put filesystem like this `mountFs:{files}`

I am required to do this 

```js

import { readFileSync, readFile, writeFileSync } from 'node:fs'
async function run(){
readFile('./textFile.txt', 'utf8', (err, data) => {
  if (err) throw err;
  console.log(data);
});

console.log(readFileSync('./textFile.txt'))
}
await run()
```

that works correctly... But when using relative imports... Like below (in same file system):

```js

import { relativeImportFunction } from './custom.js';

console.log(relativeImportFunction());
```

Error:  "Module '/node_modules/custom.js' not installed or available".

Which not sure why readSync didn't look in src but index of your vfs...?

**Comment by sebastianwessel** [comment] 2024-08-20 13:59
Looks like an issue with `setModuleLoader`.
Do you use some custom loader?

**Comment by MarketingPip** [comment] 2024-08-20 14:02
Yes @sebastianwessel - using my own FS. The filesystem looks like this:

```js
{
    "test.cpp": "// C++ program to display \"Hello World\"\n  \n// Header file for input output functions\n#include <iostream>\nusing namespace std;\n  \n// Main() function: where the execution of program begins\nint main()\n{\n    // prints hello world\n    cout << \"Hello World\";\n  \n    return 0;\n}",
    "test.ts": "function sayHello(name: string): string {\n    return `Hello, ${name}!`;\n}\n\nconst message = sayHello('World');\nconsole.log(message);\n",
    "hello.php": "<?php\necho \"Hello, World!\";\n?>\n",
    "hello.js": "console.log(\"Hello, World!\");",
    "hello.coffee": "console.log 'Hello, World!'",
    "ansi.js": "const redText = '\u001b[31mThis text is red\u001b[0m';\nconst greenText = '\u001b[32mThis text is green\u001b[0m';\n\n// Log colored text\nconsole.log(redText);\nconsole.log(greenText);",
    "custom.js": "export const relativeImportFunction = ()=>'Hello from relative import function'",
    "main.js": "\nimport { relativeImportFunction } from './custom.js';\n\nconsole.log(relativeImportFunction());\n",
    "textFile.txt": "Hello from the text file!",
    "main2.js": "\nimport { readFileSync, readFile, writeFileSync } from 'node:fs'\nasync function run(){\nreadFile('./src/textFile.txt', 'utf8', (err, data) => {\n  if (err) throw err;\n  console.log(data);\n});\n\nconsole.log(readFileSync('./src/textFile.txt'))\n}\nawait run()\n",
    "fetch.js": "async function getRepoData(owner, repo) {\n  const url = `https://api.github.com/repos/${owner}/${repo}`;\n  \n  try {\n    const response = await fetch(url);\n\n    if (!response.ok) {\n      throw new Error(`GitHub API error: ${response.statusText}`);\n    }\n\n    const data = await response.json();\n    console.log('Repository Data:', data);\n  } catch (error) {\n    console.error(error.message);\n  }\n}\n\nawait getRepoData('octocat', 'Hello-World'); // Replace with the desired owner and repo",
    "fetch_placeholders.js": "async function getJsonPlaceholderData(resource, id) {\n  const url = `https://jsonplaceholder.typicode.com/${resource}/${id}`;\n  \n  try {\n    const response = await fetch(url);\n\n    if (!response.ok) {\n      throw new Error(`API error: ${response.statusText}`);\n    }\n\n    const data = await response.json();\n    console.log('${resource} Data:', data);\n  } catch (error) {\n    console.error(error.message);\n  }\n}\n\nawait getJsonPlaceholderData('posts', 1); // Replace 'posts' and '1' with the desired resource and ID",
    "": {},
    "etc": {
        "motd": "Welcome to the Unix-like virtual filesystem!"
    },
    "var": {
        "log": {
            "syslog": "System log initialized."
        }
    },
    "home": {
        "user": {
            "README.txt": "This is the home directory of the user."
        }
    }
}
```

Feel free to more to hack around - play with a live demo [here](https://codepen.io/MarketingPipeline/pen/XWLzXoL?editors=1111).  Try using `node main.js` or `nano main.js`. (things are little buggy with nano etc lol.

 Add some of your god like code / commits to project too (would like to make that pen a real thing hahah!)

**Comment by MarketingPip** [comment] 2024-08-20 14:27
If the file was executed in {src}... When used like `mountFs{src:myVFS as json above}`.

I am required to do this... 

```js
import {test} from "./src/test.js"
```

which being `main.js` is in "root" of vfs... same with test.js.  Which in Node.js would be / should be.

```js
import {test} from "./test.js"
```

since main.js is the entry point and is in the "root" ie: "src". as well "test.js" is in "src" ie my "root". 

So I guess to better phrase my issue. Can we set the "cwd" via option or can we just do this by setting process env for path / cwd?

Apologizes too for so many issues (but read through documentation thoroughly lol)

**Comment by sebastianwessel** [comment] 2024-08-20 14:46
`evalCode` has 3 parameters.
1. is the code
2. is the filename and location for the executed code (default src/index.js)
3. evalOptions (like timeout)

So, it you can already set it like `evalCode(code, '/main.js')`, but is not recommended.
I highly recommend mount any source file below `src` and to keep the defaults.

The structure should be something like:

```
src/
  main.js
  test.js
  custom.js
  ...
```

**Comment by sebastianwessel** [comment] 2024-08-21 00:04
## This is not expected

```ts
import { relativeImportFunction } from './custom.js'; // in src folder

console.log(readFileSync('./textFile.txt'))  // both in src
```

## Expected

```ts
import { relativeImportFunction } from './custom.js'; // in src folder, as it is relative to the eval code, which is per default src/index.js

console.log(readFileSync('./textFile.txt'))  // in root, not in src as cwd is root
```

**Comment by MarketingPip** [comment] 2024-08-21 00:15
@sebastianwessel - huh?

**Comment by sebastianwessel** [comment] 2024-08-21 09:05
File structure:

```
|- textFile.txt
|- src
     |- index.js
     |- custom.js
```

When you execute the script - which is seen as `src/index.js`, it is - same as you would do `node ./src/index.js`.
The import is relative to the file which imports another file. When you import `custom.js` from `index.js`, it is `./custom.js`, as they are in the same folder, and it does not matter where they are - only the relative location does matter.

Read file on the other hand is NOT relative to the source file. It is relative to the current user location, which is the root of the file system.
Means, if the file `textFile.txt` is in the root, it is `./textFile.txt`, if it is in `/src`, it must be `./src/textFile.txt`, if it is in `public`, it must be `./public/textFile.txt`.
Something like `../textFile.txt` is invalid, as you are already in the most top location.

This fixed behavior makes it simple, as you do not need to struggle with something like `__dirname`, `process.cwd()`, `import.meta.url`. It simply removes the need for bulls*it like:

```typescript
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
    
const __dirname = dirname(fileURLToPath(import.meta.url));
```

That is the expected behavior of this lib.
If it is not working like this, then it is a bug. As I have limited resources, I need to keep focus very hard. This means, if there is a bug in the current version, it will be fixed in the upcoming version, which is a refactored one, with a bunch of new possibilities, but also a bunch of breaking changes.

**Closed** 2024-09-10 23:13 UTC

**Comment by MarketingPip** [comment] 2024-09-11 00:40
@sebastianwessel - is there any way we could add support for not having to do this. So developers don't get confused say if using this in a Web IDE?

**Comment by sebastianwessel** [comment] 2024-09-11 08:23
I do not get what your issue is here.
Why should someone get confused?

You mount your file system in root, you are in the root, and it is defined, that your index source, which is the currentl executed file, is located at `/src/index.[t|j]s`

**Comment by MarketingPip** [comment] 2024-09-16 04:44
@sebastianwessel - I still think there is an issue here. Tho I will report back asap and clarify any findings. 

ps - thought you might this is useful see [here](https://github.com/unjs/unenv/tree/main)
